from __future__ import annotations

import json
from pathlib import Path

from clash_relay.doctor import run_doctor


def test_fresh_fork_public_preflight_and_fictional_build(
    repo_root: Path,
    built_candidate,
    fixture_env: dict[str, str],
) -> None:
    doctor = run_doctor(
        config_path=repo_root / "config.yaml",
        subscriptions_path=repo_root / "subscriptions.yaml",
        policies_path=repo_root / "policies.yaml",
        mihomo_manifest=repo_root / "tools/mihomo-versions.json",
        public_only=True,
        env={},
    )

    assert doctor["public"]["policy_model_version"] == 2
    assert doctor["public"]["policy_model_status"] == "current"
    assert doctor["guidance"]["first_publish_default"] is False
    assert doctor["guidance"]["enabled_subscription_secrets"] == [
        "SUBSCRIPTION_1_URL",
        "SUBSCRIPTION_2_URL",
        "SUBSCRIPTION_3_URL",
        "SUBSCRIPTION_4_URL",
    ]

    assert built_candidate.report["successful_subscriptions"] == 3
    assert built_candidate.report["usable_nodes"] > 0
    assert built_candidate.config["proxy-providers"]
    assert built_candidate.config["proxy-groups"]
    assert built_candidate.yaml_text.startswith("# Generated by clash-relay")

    serialized_report = json.dumps(built_candidate.report, sort_keys=True)
    assert all(secret not in built_candidate.yaml_text for secret in fixture_env.values())
    assert all(secret not in serialized_report for secret in fixture_env.values())


def test_fresh_fork_release_authority_is_composed_from_existing_gates(repo_root: Path) -> None:
    validate = (repo_root / ".github" / "workflows" / "validate.yml").read_text(encoding="utf-8")
    publish = (repo_root / ".github" / "workflows" / "publish.yml").read_text(encoding="utf-8")
    rollback = (repo_root / ".github" / "workflows" / "rollback.yml").read_text(
        encoding="utf-8"
    )

    assert 'python: ["3.11", "3.12", "3.13"]' in validate
    assert "Deterministic fictional generation" in validate
    assert "Export pinned stable Mihomo matrix" in validate
    assert "Real startup and provider HEAD integration tests" in validate
    assert "Validated SHA" in validate

    assert "needs.validate.outputs.validated_sha == github.sha" in publish
    assert 'ref: ${{ needs.validate.outputs.validated_sha }}' in publish
    assert "CLASH_RELAY_VALIDATED_SHA" in publish
    assert "run_production_release.py" in publish

    assert "tools/mihomo-versions.json" in rollback
    assert "audit_production.py" in rollback
    assert "validate_mihomo_matrix.py" in rollback
    assert "--allow-legacy-openai-client-path" not in rollback
