from __future__ import annotations

import json
from pathlib import Path

import pytest
import yaml

from clash_relay.builder import build_candidate
from clash_relay.errors import GenerationError
from clash_relay.util import dump_yaml


def _groups(config: dict) -> dict[str, dict]:
    return {item["name"]: item for item in config["proxy-groups"]}


def _provider_servers(config: dict, prefix: str) -> set[str]:
    servers: set[str] = set()
    for name, provider in config["proxy-providers"].items():
        if name.startswith(prefix):
            servers.update(item["server"] for item in provider["payload"])
    return servers


def _build(paths: dict[str, Path], env: dict[str, str]):  # noqa: ANN202
    return build_candidate(**paths, env=env)


def test_fictional_end_to_end_build(built_candidate) -> None:
    assert built_candidate.report["successful_subscriptions"] == 3
    assert built_candidate.report["duplicates_removed"] == 1
    assert built_candidate.report["usable_nodes"] == 11
    assert built_candidate.yaml_text.startswith("# Generated by clash-relay")


def test_output_has_inline_providers_and_no_flat_proxies(built_candidate) -> None:
    config = built_candidate.config
    assert "proxies" not in config
    assert config["proxy-providers"]
    assert all(provider["type"] == "inline" for provider in config["proxy-providers"].values())
    assert all("url" not in provider for provider in config["proxy-providers"].values())


def test_every_provider_is_nonempty_and_health_checked(built_candidate) -> None:
    for provider in built_candidate.config["proxy-providers"].values():
        assert provider["payload"]
        assert provider["health-check"]["enable"] is True
        assert provider["health-check"]["url"].startswith("https://")
        assert provider["health-check"]["expected-status"]


def test_layering_is_public_to_fallback_to_auto_to_provider(built_candidate) -> None:
    config = built_candidate.config
    groups = _groups(config)
    for public in [item for item in config["proxy-groups"] if not item.get("hidden", False)]:
        assert public["type"] == "select"
        assert len(public["proxies"]) == 1
        fallback = groups[public["proxies"][0]]
        assert fallback["hidden"] is True
        if fallback["proxies"] == ["REJECT"]:
            continue
        assert fallback["type"] == "fallback"
        for auto_name in fallback["proxies"]:
            auto = groups[auto_name]
            assert auto["type"] == "url-test"
            assert auto["hidden"] is True
            assert all(name in config["proxy-providers"] for name in auto["use"])


def test_public_groups_are_small_and_business_facing(built_candidate) -> None:
    assert built_candidate.report["public_groups"] == [
        "Proxy",
        "ChatGPT",
        "Claude",
        "Gemini",
        "Google Play",
        "EMBY",
        "Video & Downloads",
        "Residential",
        "High Multiplier",
        "Chain",
    ]
    assert all(not name.startswith("__CR_") for name in built_candidate.report["public_groups"])


@pytest.mark.parametrize("service", ["chatgpt", "claude", "gemini"])
def test_ai_service_pool_uses_only_explicit_ai_nodes(built_candidate, service: str) -> None:
    servers = _provider_servers(built_candidate.config, f"cr_{service}_")
    assert servers
    assert all("-ai-" in server for server in servers)


def test_ai_can_select_across_subscriptions(built_candidate) -> None:
    servers = _provider_servers(built_candidate.config, "cr_chatgpt_")
    assert any(server.startswith("primary-") for server in servers)
    assert any(server.startswith("secondary-") for server in servers)


def test_ai_country_pools_are_generated(built_candidate) -> None:
    providers = built_candidate.config["proxy-providers"]
    assert "cr_chatgpt_us" in providers
    assert "cr_chatgpt_jp" in providers
    assert "cr_chatgpt_sg" in providers
    assert "cr_chatgpt_other" not in providers


def test_general_pool_excludes_ai_and_special_routes(built_candidate) -> None:
    servers = _provider_servers(built_candidate.config, "cr_general_")
    assert servers
    assert not any("-ai-" in server for server in servers)
    assert not any(server.startswith("special-") for server in servers)


def test_bulk_pool_never_uses_expensive_or_special_routes(built_candidate) -> None:
    for prefix in ("cr_bulk_", "cr_google_play_"):
        servers = _provider_servers(built_candidate.config, prefix)
        assert servers
        assert not any(server.startswith("special-") for server in servers)
        assert not any("-ai-" in server for server in servers)


@pytest.mark.parametrize(
    ("provider_prefix", "expected_server_fragment"),
    [
        ("cr_residential_", "residential"),
        ("cr_emby_", "emby"),
        ("cr_high_multiplier_", "high"),
    ],
)
def test_special_pools_are_capability_isolated(
    built_candidate, provider_prefix: str, expected_server_fragment: str
) -> None:
    servers = _provider_servers(built_candidate.config, provider_prefix)
    assert servers
    assert all(expected_server_fragment in server for server in servers)


def test_chain_is_controlled_two_hop_dialer(built_candidate) -> None:
    config = built_candidate.config
    entry = config["proxy-providers"]["cr_chain_entry_chain"]
    exits = config["proxy-providers"]["cr_chain_exit_chain"]
    assert all("dialer-proxy" not in proxy for proxy in entry["payload"])
    assert exits["payload"]
    assert {
        proxy["dialer-proxy"] for proxy in exits["payload"]
    } == {"__CR_CHAIN_ENTRY_AUTO_CHAIN"}


def test_subscription_dialer_proxy_is_stripped_before_generation(
    project_factory, fixture_env, yaml_editor
) -> None:
    root, paths = project_factory()
    source = root / "hostile.yaml"
    source.write_text(
        yaml.safe_dump(
            {
                "proxies": [
                    {
                        "name": "Hostile General",
                        "type": "http",
                        "server": "hostile.invalid.example",
                        "port": 443,
                        "dialer-proxy": "Attacker Group",
                    }
                ]
            }
        ),
        encoding="utf-8",
    )

    def one_source(document):  # noqa: ANN001
        item = document["subscriptions"][0]
        item["node_metadata"] = {}
        document["subscriptions"] = [item]

    yaml_editor(paths["subscriptions_path"], one_source)

    def general_only(document):  # noqa: ANN001
        for key in document["modules"]:
            document["modules"][key] = key == "general"

    yaml_editor(paths["config_path"], general_only)
    result = _build(paths, {"SUB_PRIMARY": source.resolve().as_uri()})
    assert all(
        "dialer-proxy" not in proxy
        for provider in result.config["proxy-providers"].values()
        for proxy in provider["payload"]
    )


def test_optional_empty_service_fails_closed(project_factory, fixture_env, yaml_editor) -> None:
    _, paths = project_factory()

    def remove_ai_metadata(document):  # noqa: ANN001
        for subscription in document["subscriptions"]:
            for metadata in subscription.get("node_metadata", {}).values():
                metadata["add_capabilities"] = [
                    cap for cap in metadata.get("add_capabilities", []) if cap != "ai"
                ]

    yaml_editor(paths["subscriptions_path"], remove_ai_metadata)
    result = _build(paths, fixture_env)
    groups = _groups(result.config)
    assert groups["__CR_SERVICE_FALLBACK_CHATGPT"]["proxies"] == ["REJECT"]
    assert not any(name.startswith("cr_chatgpt_") for name in result.config["proxy-providers"])


def test_required_general_pool_empty_aborts_build(project_factory, fixture_env, yaml_editor) -> None:
    _, paths = project_factory()

    def remove_general(document):  # noqa: ANN001
        for subscription in document["subscriptions"]:
            subscription["default_capabilities"] = []
            for metadata in subscription.get("node_metadata", {}).values():
                metadata["add_capabilities"] = [
                    cap for cap in metadata.get("add_capabilities", []) if cap != "general"
                ]

    yaml_editor(paths["subscriptions_path"], remove_general)
    with pytest.raises(GenerationError, match="required pool 'general'"):
        _build(paths, fixture_env)


@pytest.mark.parametrize("removed_id", ["primary", "secondary", "special"])
def test_deleting_any_subscription_still_generates(
    project_factory, fixture_env, yaml_editor, removed_id: str
) -> None:
    _, paths = project_factory()

    def remove(document):  # noqa: ANN001
        document["subscriptions"] = [
            item for item in document["subscriptions"] if item["id"] != removed_id
        ]

    yaml_editor(paths["subscriptions_path"], remove)
    env = {
        key: value
        for key, value in fixture_env.items()
        if key != {"primary": "SUB_PRIMARY", "secondary": "SUB_SECONDARY", "special": "SUB_SPECIAL"}[removed_id]
    }
    result = _build(paths, env)
    assert result.report["successful_subscriptions"] >= 2
    assert result.config["rules"][-1] == "MATCH,Proxy"


def test_adding_subscription_requires_no_python_change(
    project_factory, fixture_env, yaml_editor, repo_root: Path
) -> None:
    _, paths = project_factory()

    def add(document):  # noqa: ANN001
        item = dict(document["subscriptions"][1])
        item.update(id="new_source", secret_name="SUB_NEW", display_name="New Source", priority=250)
        item["node_metadata"] = {}
        document["subscriptions"].append(item)

    yaml_editor(paths["subscriptions_path"], add)
    env = dict(fixture_env)
    env["SUB_NEW"] = (repo_root / "tests/fixtures/subscriptions/secondary.yaml").resolve().as_uri()
    result = _build(paths, env)
    assert result.report["successful_subscriptions"] == 4


def test_new_ai_service_is_configuration_only(
    project_factory, fixture_env, yaml_editor
) -> None:
    root, paths = project_factory()
    (root / "rules/perplexity.yaml").write_text(
        "version: 1\nrules:\n  - {type: DOMAIN-SUFFIX, value: perplexity.ai}\n",
        encoding="utf-8",
    )

    def add_module(document):  # noqa: ANN001
        document["modules"]["perplexity"] = True

    def add_service(document):  # noqa: ANN001
        item = dict(document["services"][0])
        item.update(
            id="perplexity",
            display_name="Perplexity",
            module="perplexity",
            rules="rules/perplexity.yaml",
            rule_priority=130,
        )
        document["services"].append(item)

    yaml_editor(paths["config_path"], add_module)
    yaml_editor(paths["services_path"], add_service)
    result = _build(paths, fixture_env)
    assert "Perplexity" in result.report["public_groups"]
    assert any(name.startswith("cr_perplexity_") for name in result.config["proxy-providers"])


def test_disabling_optional_modules_removes_public_and_internal_groups(
    project_factory, fixture_env, yaml_editor
) -> None:
    _, paths = project_factory()

    def general_only(document):  # noqa: ANN001
        for name in document["modules"]:
            document["modules"][name] = name == "general"

    yaml_editor(paths["config_path"], general_only)
    result = _build(paths, fixture_env)
    assert result.report["public_groups"] == ["Proxy"]
    assert all("CHATGPT" not in group["name"] for group in result.config["proxy-groups"])


def test_generation_is_byte_deterministic(project_paths, fixture_env) -> None:
    first = _build(project_paths, fixture_env)
    second = _build(project_paths, fixture_env)
    assert first.yaml_text == second.yaml_text
    assert first.report["candidate_sha256"] == second.report["candidate_sha256"]


def test_secret_subscription_urls_never_leak(project_paths, fixture_env) -> None:
    result = _build(project_paths, fixture_env)
    assert not any(value in result.yaml_text for value in fixture_env.values())
    report = json.dumps(result.report, sort_keys=True)
    assert not any(value in report for value in fixture_env.values())


def test_rules_refer_only_to_public_groups_or_builtins(built_candidate) -> None:
    config = built_candidate.config
    public = {group["name"] for group in config["proxy-groups"] if not group.get("hidden", False)}
    builtins = {"DIRECT", "REJECT", "PASS", "COMPATIBLE"}
    for rule in config["rules"]:
        parts = rule.split(",")
        target = parts[1] if parts[0] == "MATCH" else parts[2]
        assert target in public | builtins


def test_output_round_trip_is_stable(built_candidate) -> None:
    loaded = yaml.safe_load(built_candidate.yaml_text)
    assert dump_yaml(loaded, header=True) == built_candidate.yaml_text
