"""Small deterministic and security-oriented utilities."""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any

import yaml
from yaml.tokens import AliasToken, AnchorToken

from .errors import ConfigurationError, SubscriptionError, UnsafeSubscriptionError


class _NoAliasDumper(yaml.SafeDumper):
    def ignore_aliases(self, data: object) -> bool:
        return True


_SAFE_ID_RE = re.compile(r"[^A-Za-z0-9_-]+")


def yaml_load_no_aliases(text: str, *, source: str, untrusted: bool = False) -> Any:
    """Load YAML while rejecting anchors and aliases to avoid expansion attacks."""
    if "\x00" in text:
        error = UnsafeSubscriptionError if untrusted else ConfigurationError
        raise error(f"{source}: NUL bytes are not allowed")
    try:
        for token in yaml.scan(text):
            if isinstance(token, (AliasToken, AnchorToken)):
                error = UnsafeSubscriptionError if untrusted else ConfigurationError
                raise error(f"{source}: YAML anchors and aliases are not allowed")
        return yaml.safe_load(text)
    except (yaml.YAMLError, UnicodeError) as exc:
        error = SubscriptionError if untrusted else ConfigurationError
        raise error(f"{source}: invalid YAML") from exc


def load_yaml_file(path: Path, *, untrusted: bool = False) -> Any:
    try:
        raw = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        error = SubscriptionError if untrusted else ConfigurationError
        raise error(f"cannot read {path}") from exc
    return yaml_load_no_aliases(raw, source=str(path), untrusted=untrusted)


def dump_yaml(data: Any, *, header: bool = False) -> str:
    text = yaml.dump(
        data,
        Dumper=_NoAliasDumper,
        allow_unicode=True,
        default_flow_style=False,
        sort_keys=False,
        width=120,
    )
    if header:
        return "# Generated by clash-relay. Do not edit; regenerate from declarations.\n" + text
    return text


def atomic_write(path: Path, content: str, *, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temp_name, mode)
        os.replace(temp_name, path)
    except BaseException:
        try:
            os.unlink(temp_name)
        except FileNotFoundError:
            pass
        raise


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def stable_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def safe_identifier(value: str, *, upper: bool = False, maximum: int = 64) -> str:
    normalized = _SAFE_ID_RE.sub("_", value).strip("_") or "ITEM"
    normalized = normalized.upper() if upper else normalized.lower()
    return normalized[:maximum]


def deep_size_guard(value: Any, *, max_depth: int = 20, max_items: int = 100_000) -> None:
    """Bound nested attacker-controlled subscription structures."""
    stack: list[tuple[Any, int]] = [(value, 0)]
    count = 0
    while stack:
        current, depth = stack.pop()
        count += 1
        if count > max_items:
            raise SubscriptionError("subscription structure contains too many values")
        if depth > max_depth:
            raise SubscriptionError("subscription structure is nested too deeply")
        if isinstance(current, dict):
            stack.extend((key, depth + 1) for key in current)
            stack.extend((item, depth + 1) for item in current.values())
        elif isinstance(current, (list, tuple)):
            stack.extend((item, depth + 1) for item in current)


def unique(values: list[str]) -> list[str]:
    return list(dict.fromkeys(values))
